version: '3.8'
services:
  fm-client:
    image: node:20-alpine
    container_name: fm-client
    environment:
      - NUXT_API_BASE="http://127.0.0.1:8081"
      - NUXT_API_ENDPOINT="/api"
    volumes:
      - ./config:/config
    depends_on:
      - 'zorros_fm_server'
    ports:
      - 3030:80
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
