version: '3.8'
services:
  zorros_fm_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fm-client
    command: pm2 start ecosystem.config.cjs
    environment:
      - NUXT_API_BASE="http://127.0.0.1:8081"
      - NUXT_API_ENDPOINT="/api"
    ports:
      - 3030:3030
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
