services:
  zorros_fm_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fm-client
    command: pm2 start ecosystem.config.cjs
    ports:
      - 3030:3030
    networks:
      - reverse_proxy
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
